# Generated by Django 2.0.7 on 2018-07-29 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apostila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sem Título', max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='Autor')),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, unique=True, upload_to='')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='URL para Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='apostila',
            name='categories',
            field=models.ManyToManyField(to='Materials.Categoria'),
        ),
        migrations.AddField(
            model_name='apostila',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.Project'),
        ),
    ]
