# Generated by Django 2.0.7 on 2018-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Materials.Categoria'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Materials.Project'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL para Documento'),
        ),
    ]
