# Generated by Django 2.0.7 on 2018-07-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0002_auto_20180731_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
