# Generated by Django 2.0.7 on 2018-07-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0003_auto_20180731_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Materials.Project'),
        ),
    ]
