# Generated by Django 2.0.7 on 2018-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0005_auto_20180731_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='file',
            field=models.FileField(blank=True, help_text='Se estiver modificando o arquivo da Apostila, NÃO SELECIONE limpar e outro arquivo ao mesmo tempo.', upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
