# Generated by Django 2.0.7 on 2018-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0006_auto_20180731_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='file',
            field=models.FileField(blank=True, help_text='Se estiver modificando o arquivo da Apostila, NÃO SELECIONE limpar e outro arquivo ao mesmo tempo.', upload_to='None', verbose_name='Arquivo'),
        ),
    ]
