# Generated by Django 2.0.7 on 2018-08-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0008_auto_20180801_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='file',
            field=models.FileField(blank=True, help_text='Se estiver modificando o arquivo da Apostila, NÃO SELECIONE limpar e outro arquivo ao mesmo tempo.', upload_to=''),
        ),
    ]
