# Generated by Django 2.1 on 2019-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0010_auto_20180807_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='project',
            field=models.ManyToManyField(blank=True, help_text='Opcional. Adicione se a apostila faz parte de algum projeto.', to='Materials.Project'),
        ),
    ]
